-- 1. 회원 테이블 drop (테이블이 있을경우)
DROP TABLE IF EXISTS DOMAIN.MEMBER CASCADE;

-- 2. 스키마 생성
CREATE SCHEMA DOMAIN;

-- 2. 회원 테이블 생성
CREATE TABLE DOMAIN.MEMBER (
    ID          SERIAL        PRIMARY KEY
  , NAME        VARCHAR(50)   NOT NULL
)
;

COMMENT ON TABLE DOMAIN.MEMBER IS '회원';

COMMENT ON COLUMN DOMAIN.MEMBER.ID IS '회원ID@pk';
COMMENT ON COLUMN DOMAIN.MEMBER.NAME IS '이름';